stages:
  - build
  - test

# Install build-essential for dependencies
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential
  - apt-get install -yqq pkg-config
  - apt-get install -yqq libssl-dev


build-stable:
  image: scorpil/rust:stable
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target

test-stable:
  image: scorpil/rust:stable
  stage: test
  dependencies:
    - build-stable
  script:
    - cargo test
