[package]
name = "inspirer"
authors = ["Nathan Musoke <nathan.musoke@gmail.com>"]
version = "0.1.0-alpha"

[dependencies]
clap = "2.20.0"
regex = "0.2"
reqwest = "0.5.0"
select = "0.3.0"
slog = "1.4.1"
slog-stdlog = "1.1.0"
slog-term = "1.4.0"
