name: inspirer # you probably want to 'snapcraft register <name>'
version: '0.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: For fetching BibTeX entries from INSPIRE and ADS
description: |
  For fetching BibTeX entries from INSPIRE and ADS
  https://crates.io/crates/inspirer

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  aux2bib:
    command: bin/aux2bib
    plugs:
      - network
      - home
  blg2bib:
    command: bin/blg2bib
    plugs:
      - network
      - home

parts:
  bins:
    plugin: rust
    rust-channel: stable
    stage-packages:
      - pkg-config
      - libssl-dev
